services:
  BareMetalArduino:
    image: bare_metal_arduino
    build: .
    container_name: bare-metal-arduino-container
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - ./:/app